---
platform: linux
inputs:
- name: stratos
- name: helm-chart-tarball
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository: splatform/ci-stratos-github-release
   tag: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      # Create Github release
      ROOT_DIR=${PWD}
      VERSION=$(cat image-tag/v2-version)
      FULL_VERSION=$(cat image-tag/v2-alpha-tag)
      cd ${ROOT_DIR}/stratos
      GIT_TAG="$(git describe $(git rev-list --tags --max-count=1))"
      cd ${ROOT_DIR}/helm-chart-tarball
      CHART_PACKAGE=$(ls *.tgz)

      # Upload Helm chart to release
      github-release release -t ${FULL_VERSION} --name "Stratos ${VERSION} Preview release" --pre-release
      github-release upload -t ${FULL_VERSION} --file ${CHART_PACKAGE} --name "${CHART_PACKAGE}"
      