---
platform: linux
inputs:
- name: stratos
- name: helm-chart-tarball
- name: image-tag
image_resource:
  type: docker-image
  source:
   repository: splatform/ci-stratos-github-release
   tag: "latest"

run:
  path: sh
  args:
    - -exc
    - |
      # Create Github release
      ROOT_DIR=${PWD}
      cd ${ROOT_DIR}/stratos
      GIT_TAG=$(cat ../image-tag/v2-alpha-tag)
      cd ${ROOT_DIR}/helm-chart-tarball
      CHART_PACKAGE=$(ls *.tgz)
      # Upload Helm chart to release
      github-release release -t ${GIT_TAG} --name "Stratos ${GIT_TAG} Preview release" --pre-release
      github-release upload -t ${GIT_TAG} --file ${CHART_PACKAGE} --name "console-helm-chart-${GIT_TAG}.tgz"