language: node_js
node_js:
  - "12.13.0"
sudo: required
dist: bionic
services:
  - docker
addons:
  chrome: stable
before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1366x768x24"
  - sleep 3
install:
  - npm install
  - ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
filter_secrets: false
branches:
  only:
    - master
    - v2-master
    - e2e-tests
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
    - node_modules
stages:
  - Lint
  - Build
  - Test
jobs:
  include:
    - stage: Test
    - name: E2E Tests - Long Suites
      before_script:
        - "./deploy/ci/travis/job-e2e-before_script.sh"
      script:
        - "./deploy/ci/travis/job-e2e-script.sh longSuite"
