apiVersion: v1
kind: PersistentVolume
metadata:
  name: console-pv-rwo1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /data/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: console-pv-rwo2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /data/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: console-pv-rwm
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/
