{{- if not .Values.noShared }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
  name: "{{ .Release.Name }}-postflight-job"

spec:
 template:
     metadata:
       labels:
         app: "{{ .Release.Name }}"
         job: postflight
     spec:
       containers:
        - env:
          - name: PGSQL_HOST
            value: "{{ .Release.Name }}-postgres-int"
          - name: PGSQL_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD_FILE
            value: /etc/secrets/stolon
          - name: PGSQL_DATABASE
            value: console-db
          - name: PGSQL_USER
            value: console
          - name: PGSQL_PASSWORDFILE
            value: /etc/secrets/pgsql-password
          - name: PGSQL_SSL_MODE
            value: disable
          - name: PGCONNECT_TIMEOUT
            value: "10"
          - name: UPGRADE_VOLUME
            value: "{{ .Release.Name }}-upgrade-volume"
          - name: UPGRADE_LOCK_FILENAME
            value: upgrade.lock
          - name: HTTP_PROXY
          {{- if .Values.httpProxy }}
            value: {{.Values.httpProxy}}
          {{- end }}
          - name: HTTPS_PROXY
          {{- if .Values.httpsProxy }}
            value: {{.Values.httpsProxy}}
          {{- end }}
          - name: NO_PROXY
          {{- if .Values.noProxy }}
            value: {{.Values.noProxy}}
          {{- end }}
          - name: FTP_PROXY
          {{- if .Values.ftpProxy }}
            value: {{.Values.ftpProxy}}
          {{- end }}
          - name: SOCKS_PROXY
          {{- if .Values.socksProxy }}
            value: {{.Values.socksProxy}}
          {{- end }}
          image: {{.Values.dockerRegistry}}/{{.Values.dockerOrg}}/{{.Values.images.postflight}}:{{.Values.consoleVersion}}
          name: "{{ .Release.Name }}-postflight-job"
          volumeMounts:
          - mountPath: "/{{ .Release.Name }}-upgrade-volume"
            name: "{{ .Release.Name }}-upgrade-volume"
          - mountPath: /etc/secrets/
            name: "{{ .Release.Name }}-secret"
       restartPolicy: OnFailure
       volumes:
       - name: "{{ .Release.Name }}-upgrade-volume"
         persistentVolumeClaim:
           claimName: "{{ .Release.Name }}-upgrade-volume"
       - name: "{{ .Release.Name }}-secret"
         secret:
           secretName: "{{ .Release.Name }}-secret"
{{- end }}
