apiVersion: v1
kind: Service
metadata:
{{- if .Values.console.service.annotations }}
  annotations:
{{ toYaml .Values.console.service.annotations | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-ext-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: "{{ .Release.Name }}-ui-ext"
spec:
{{- if .Values.console.service.clusterIP }}
  clusterIP: {{ .Values.console.service.clusterIP }}
{{- end }}
{{- if or .Values.console.service.externalIPs .Values.kube.external_ip .Values.console.externalIP .Values.kube.external_ips }}
  externalIPs:
  {{ template "service.externalIPs" . }}
{{- end }}
{{- if .Values.console.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.console.service.loadBalancerIP }}
{{- end }}
{{- if .Values.console.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.console.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if .Values.console.service.externalName }}
  externalName: {{ .Values.console.service.externalName }}
{{- end }}

# Note: HTTP Port is optional - HTTPS port is always included
# HTTP Service (optional)
  ports:
{{- if .Values.console.service.http.enabled }}
  - name: http
    port: {{ .Values.console.service.http.servicePort }}
    protocol: TCP
    targetPort: 80
    {{- if .Values.console.service.http.nodePort }}
    nodePort: {{ .Values.console.service.http.nodePort }}
    {{- end }}    
{{- end }}
# HTTPS Service
  - name: https
    port: {{ template "service.servicePort" . }}
    protocol: TCP
    targetPort: 443
    {{- if .Values.console.service.nodePort }}
    nodePort: {{ .Values.console.service.nodePort }}
    {{- end }}
  type: {{ template "service.serviceType" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mariadb"
  labels:
    app.kubernetes.io/name: "stratos"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "console-mariadb-service"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ .Release.Name }}"


