---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   # Image based on bosh/cli2 with git and go added
   repository:  registry.capbristol.com:5000/stratos-concourse
   tag: "latest"
   insecure_registries: ["registry.capbristol.com:5000"]

run:
  path: sh
  args:
    - -xc
    - |
      FRONTEND_IP=${CONSOLE_ADDRESS}
      ping -c5 ${FRONTEND_IP}
      cd stratos-ui
      npm install
      export PATH=${PWD}/node_modules/.bin:$PATH
      bower install --allow-root --force

      cat << EOF > build/secrets.json
      {
        "cloudFoundry": {
          "url": "${CF_API_URL}",
          "admin": {
            "username": "${CF_ADMIN_USER}",
            "password": "${CF_ADMIN_PASSWORD}"
          },
          "user": {
            "username": "${CF_E2E_USER}",
            "password": "${CF_E2E_USER_PASSWORD}"
          }
       },
        "console": {
          "host": "${FRONTEND_IP}",
          "port": "443",
          "admin": {
            "username": "${CF_ADMIN_USER}",
            "password": "${CF_ADMIN_PASSWORD}"
          },
          "user": {
            "username": "${CF_E2E_USER}",
            "password": "${CF_E2E_USER_PASSWORD}"
          }
        },
        "uaa": {
          "url": "${UAA_URL}",
          "clientId": "${UAA_CLIENT_ID}",
          "adminUsername": "${UAA_ADMIN_USERNAME}",
          "adminPassword": "${UAA_ADMIN_PASSWORD}"
        },
        "runSetupModeTests": true,
        "githubPat": "${GITHUB_TOKEN}"
      }
      EOF

      cat build/secrets.json
      export DBUS_SESSION_BUS_ADDRESS=/dev/null
      npm run update-webdriver
      xvfb-run --server-args='-screen 0 1920x1080x24' protractor ./build/protractor.conf.js --params.host=${FRONTEND_IP} --params.port=443
      exit $?