---
platform: linux
image_resource:
  type: docker-image
  source:
    repository:  registry.capbristol.com:5000/splatform/stratos-proxy-builder
    tag: "latest"
    insecure_registries: [ "registry.capbristol.com:5000" ]

inputs:
- name: stratos-ui
outputs:
- name: portal-proxy-output
run:
  path: sh
  args:
  - -exc
  - |
    cd stratos-ui
    cp -r /node_modules .
    if [ "$(md5sum /package.json | cut -d' ' -f1)" != "$(md5sum package.json| cut -d' ' -f1)" ]; then
        echo -e "\033[31mpackage.json was updated, please update the image. Running npm install\033[0m"
        npm install
      else
        echo -e "\033[32mpackage.json has not changed. Skipping npm install\033[0m"
    fi
    npm install
    npm run build-backend
    cd -
    cp -r ./stratos-ui/outputs ./portal-proxy-output
    sh ./stratos-ui/deploy/tools/generate_cert.sh
