---
platform: linux
image_resource:
  type: docker-image
  source:
    repository:  ci-registry.capbristol.com:5000/splatform/stratos-proxy-builder
    tag: "opensuse"
    insecure_registries: [ "ci-registry.capbristol.com:5000" ]

inputs:
- name: stratos-ui
outputs:
- name: portal-proxy-output
run:
  path: sh
  args:
  - -exc
  - |
    cd stratos-ui
    npm install --production
    npm run build-backend
    cd -
    cp -r ./stratos-ui/outputs ./portal-proxy-output
    sh ./stratos-ui/deploy/tools/generate_cert.sh
