---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository: 10.84.93.11:5000/portal-proxy-test
   tag: "latest"
   insecure_registries: [ "10.84.93.11:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      cd stratos-ui
      npm install
      npm run test-backend