# Stable image build pipeline
# This pipeline builds the stable Docker images for Docker Compose and AIO when the stable tag is updated
---
resource_types:
- name: docker-image
  type: docker-image
  privileged: true
  source:
    repository: ((docker-resource-image))
    tag: ((docker-resource-image-tag))

resources:
# Stratos Git Repository
- name: stratos
  type: stratos-git-resource
  source:
    uri: git@github.com:((stratos-repository-organization))/((stratos-repository))
    branch: ((stratos-repository-branch))
    private_key: ((github-private-key))
    # Match stable tag
    tag_filter: "stable"
- name: aio-docker-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: splatform/stratos
# Docker Images
- name: jetstream-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-dc-jetstream
- name: dc-db-migrator-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-dc-db-migrator
- name: mariadb-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-dc-mariadb
- name: ui-dc-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-dc-console
groups:
- name: tests
  jobs:
  - build-dc-images
  - build-aio-image

jobs:
- name: build-dc-images
  plan:
  - get: stratos
    trigger: true
  - aggregate:
    - do:
      - put: jetstream-dc-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  dev-build
          tag: stratos/deploy/ci/tasks/build-images/stable-tag
      - put: dc-db-migrator-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  db-migrator
          tag: stratos/deploy/ci/tasks/build-images/stable-tag
      - put: mariadb-dc-image
        params:
          dockerfile: stratos/deploy/db/Dockerfile.mariadb
          build: stratos/deploy/db
          tag: stratos/deploy/ci/tasks/build-images/stable-tag
      - put: ui-dc-image
        params:
          dockerfile: stratos/deploy/Dockerfile.ui
          build: stratos/
          target_name: prod-build
          tag: stratos/deploy/ci/tasks/build-images/stable-tag
      timeout: 2h30m

- name: build-aio-image
  public: true
  serial: true
  plan:
  - get: stratos
    trigger: true
  - put: aio-docker-image
    params:
      build: stratos
      dockerfile: stratos/deploy/Dockerfile.all-in-one
      tag: stratos/deploy/ci/tasks/build-images/stable-tag
