resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    uri: git@github.com:SUSE/stratos-ui.git
    private_key: {{github-private-key}}
    tag_filter: "[0-9]*"
- name: helm-charts-repository
  type: git
  source:
    branch: master
    private_key: {{github-private-key}}
    uri: {{release-helm-repo}}
- name: helm-chart-values
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-tarball
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/console-(?P<version>.*).tgz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-values-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-tarball-sle
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/console-(?P<version>.*).tgz
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1

groups:
- name: tests
  jobs:
  - build-opensuse-helm-images
  - build-sle-helm-images
  - update-repo
  - create-sle-chart
  - update-github-release
  - sync-sle-release

jobs:
- name: build-opensuse-helm-images
  plan:
  - get: stratos-ui
    trigger: true
    passed: [create-sle-chart]
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 50m
      file: stratos-ui/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
        BASE_IMAGE: opensuse
    - put: helm-chart-values
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read
- name: build-sle-helm-images
  plan:
  - get: stratos-ui
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 50m
      file: stratos-ui/deploy/ci/tasks/release/build-helm.yml
      params:
        DOCKER_USERNAME: {{staging-repository-username}}
        DOCKER_PASSWORD: {{staging-repository-password}}
        BASE_IMAGE: {{staging-repo-base-image-tag}}
        STAGING_REPOSITORY: {{staging-repository}}
        IS_OFFICIAL: "true"
    - put: helm-chart-values-sle
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart-sle
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read


- name: update-repo
  plan:
  - get: stratos-ui
    passed: [build-opensuse-helm-images]
    trigger: true
  - get: helm-chart-Chart
    passed: [build-opensuse-helm-images]
  - get: helm-chart-values
    passed: [build-opensuse-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/create-chart.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GITHUB_ORG: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
        GIT_PRIVATE_KEY: {{github-private-key}}
    - put: helm-chart-tarball
      params:
        file: helm-chart/*.tgz
        acl: public-read

- name: create-sle-chart
  plan:
  - get: stratos-ui
    passed: [build-sle-helm-images]
    trigger: true
  - get: helm-chart-Chart-sle
    passed: [build-sle-helm-images]
  - get: helm-chart-values-sle
    passed: [build-sle-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/create-chart-sle.yml
      params:
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GITHUB_ORG: {{github-organization}}
        GITHUB_REPO: {{github-repository}}
        GIT_PRIVATE_KEY: {{github-private-key}}
        BASE_IMAGE: "sle"
    - put: helm-chart-tarball-sle
      params:
        file: helm-chart/*.tgz
        acl: public-read

- name: update-github-release
  plan:
  - get: stratos-ui
    passed: [update-repo]
    trigger: true
  - get: helm-chart-tarball
    passed: [update-repo]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/update-gh-release.yml
      params:
        GITHUB_TOKEN: {{github-access-token}}
        CHANDLER_GITHUB_API_TOKEN: {{github-access-token}}
        GITHUB_USER: {{github-organization}}
        GITHUB_REPO: {{github-repository}}

- name: sync-sle-release
  plan:
  - get: stratos-ui
    passed: [create-sle-chart]
    trigger: true
  - get: helm-charts-repository
    passed: [update-github-release]
  - get: helm-chart-Chart-sle
    passed: [build-sle-helm-images]
  - get: helm-chart-values-sle
    passed: [build-sle-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/sync-official-release.yml
      params:
        GITHUB_TOKEN: {{github-access-token}}
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GIT_PRIVATE_KEY: {{github-private-key}}
        STAGING_REPOSITORY: {{staging-repository}}
        STAGING_REPOSITORY_USERNAME: {{staging-repository-username}}
        STAGING_REPOSITORY_PASSWORD: {{staging-repository-password}}
        STAGING_REPOSITORY_ORG: {{staging-repository-organization}}
        RELEASE_REPOSITORY: {{release-repository}}
        RELEASE_REPOSITORY_USERNAME: {{release-repository-username}}
        RELEASE_REPOSITORY_PASSWORD: {{release-repository-password}}
        RELEASE_REPOSITORY_ORG: {{release-repository-organization}}
        RELEASE_HELM_STABLE_FOLDER: {{release-helm-stable-folder}}
        RELEASE_SCRIPT: {{release-script}}
