resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    private_key: {{github-private-key}}
    uri: git@github.com:suse/stratos-ui.git
- name: after-midnight
  type: time
  source:
    start: 01:00 AM
    stop: 2:00 AM
    location: UTC
- name: helm-chart-values
  type: s3
  source:
    bucket: concourse-stratos-ui
    endpoint: {{minio-server-endpoint}}
    regexp: temp-artifacts/values.yaml-(?P<version>.*)
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: helm-chart-Chart
  type: s3
  source:
    bucket: concourse-stratos-ui
    regexp: temp-artifacts/Chart.yaml-(?P<version>.*)
    endpoint: {{minio-server-endpoint}}
    access_key_id: {{minio-access-key}}
    secret_access_key: {{minio-secret-access-key}}
    region_name: eu-central-1
- name: send-email
  type: email
  source:
    smtp:
      host: {{email-server}}
      port: {{email-port}}
      username: {{email-username}}
      password: {{email-password}}
    from: {{email-from}}
    to: [ ]
groups:
- name: tests
  jobs:
  - build-helm-images
  - deploy-helm

jobs:
- name: build-helm-images
  plan:
  - get: stratos-ui
  - get: after-midnight
    trigger: true
  - do:
    - task: generete-certs
      timeout: 2m
      file: stratos-ui/deploy/ci/tasks/build-images/generate-certs.yml
    - task: build
      privileged: true
      timeout: 45m
      file: stratos-ui/deploy/ci/tasks/helm/build-helm.yml
      params:
        DOCKER_USERNAME: {{docker-username}}
        DOCKER_PASSWORD: {{docker-password}}
      on_failure:
        put: send-email
        params:
          subject_text: "Helm Deploy ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} failed!"
          body_text: "Helm Deploy build has failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
    - put: helm-chart-values
      params:
        file: helm-build/values.yaml-*
        acl: public-read
    - put: helm-chart-Chart
      params:
        file: helm-build/Chart.yaml-*
        acl: public-read
  
- name: deploy-helm
  plan:
  - get: stratos-ui
    passed: [build-helm-images]
    trigger: true
  - get: helm-chart-Chart
    passed: [build-helm-images]
  - get: helm-chart-values
    passed: [build-helm-images]
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/helm/deploy-chart.yml
      params:
        CAASP_KUBE_CONFIG_URL: {{caasp-kube-config-url}}
        CAASP_NODE_IPS: {{caasp-node-ips}}
        UAA_ADMIN_PASSWORD: {{uaa-admin-password}}
        UAA_ADMIN_USERNAME: {{uaa-admin-username}}
        UAA_CLIENT_ID: {{uaa-client-id}}
        UAA_URL: {{uaa-url}}
        CF_LOCATION: {{cf-location}}
        CF_ADMIN_USER: {{cf-admin-user}}
        CF_ADMIN_PASSWORD: {{cf-admin-password}}
        CF_E2E_USER: {{cf-e2e-user}}
        CF_E2E_USER_PASSWORD: {{cf-e2e-user-password}}
        CONSOLE_ADMIN_USER: {{console-admin-user}}
        CONSOLE_ADMIN_PASSWORD: {{console-admin-password}}
        CONSOLE_USER_USER: {{console-user-user}}
        CONSOLE_USER_PASSWORD: {{console-user-password}}
        GITHUB_TOKEN: {{github-access-token}}
      on_failure:
        put: send-email
        params:
          subject_text: "Helm Deploy ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} failed!"
          body_text: "Helm Deploy build has failed: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      on_success:
        put: send-email
        params:
          subject_text: "Helm Deploy ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME} successful"
          body_text: "Helm Deploy build was successful: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
