resources:
- name: stra2ous
  type: git
  source:
    branch: master
    uri:  https://github.com/KlapTrap/stra2ous

jobs:
- name: unit-tests
  plan:
  - get: stra2ous
    trigger: true
  - do:
    - task: run-unit-tests
      privileged: true
      timeout: 5m
      file: stra2ous/deploy/ci/tasks/run-unit-tests.yml