---
platform: linux
inputs:
- name: stratos-ui
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.capbristol.com:5000/concourse-dcind
   tag: "latest"
   insecure_registries: [ "ci-registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      cd stratos-ui/deploy/ci/scripts
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      
      ./build_bk_concourse_image.sh

      docker tag docker.io/splatform/stratos-bk-concourse:${TAG} ci-registry.capbristol.com:5000/splatform/stratos-bk-concourse:latest
      docker push ci-registry.capbristol.com:5000/splatform/stratos-bk-concourse:latest


