version: '2'
services:

  ##############################################################################
  # These two "services" are not meant to be instantiated, but instead extended.
  # Unfortunately, this is necessary for those working at the HPE office where
  # the proxy is a sad, Sad, SAD way of life.
  ##############################################################################

  imageCommon:
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}


  buildCommon:
    extends: imageCommon
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}

  ##############################################################################


  postgres:
    extends: imageCommon
    image: postgres:latest
    env_file:
      ./postgres.env
    ports:
      - "5432:5432"


  goose:
    extends: buildCommon
    build:
      context: ../stratos-ui
      dockerfile: db/Dockerfile.goose.dev


  proxy:
    extends: buildCommon
    build:
      context: ../stratos-ui
      dockerfile: tools/Dockerfile.bk.dev
    ports:
      - "3003:3003"
    env_file:
      ./proxy.env
    volumes:
      - ./hsc-upgrade-volume:/hsc-upgrade-volume


  nginx:
    extends: buildCommon
    build:
      context: ../stratos-ui/containers/nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../stratos-ui/dist:/usr/share/nginx/html:ro


  ui:
    extends: buildCommon
    build:
      context: ../stratos-ui
      dockerfile: tools/Dockerfile.ui.dev
      args:
        - USER_ID
        - GROUP_ID
        - USER_NAME
    volumes:
      - ../stratos-ui:/usr/src/app

  uaa:
    extends: imageCommon
    image: susetest/uaa:latest

