version: '2.3'
services:

  mariadb:
    extends:
      file: common.yml
      service: mariadb

  db-migrator:
    extends:
      file: common.yml
      service: db-migrator
    links:
      - mariadb:mariadb

  proxy:
    extends:
      file: common.yml
      service: proxy
    links:
      - db-migrator:db-migrator
      - uaa:uaa

  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy:proxy

  uaa:
    extends:
      file: common.yml
      service: uaa
