version: '2'
services:

  # The development docker-compose file. Starts everything but the UI, useful to run with "gulp dev"

  postgres:
    extends:
      file: common.yml
      service: postgres


  goose:
    extends:
      file: common.yml
      service: goose
    links:
      - postgres:postgres


  proxy:
    extends:
      file: common.yml
      service: proxy
    links:
      - goose:goose
      - uaa:uaa


  nginx:
    extends:
      file: common.yml
      service: nginx
    links:
      - proxy:proxy

  uaa:
    extends:
      file: common.yml
      service: uaa
