---
platform: linux
inputs:
- name: stratos
- name: dev-certs-output
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.capbristol.com:5000/concourse-dcind
   tag: "latest"
   insecure_registries: [ "ci-registry.capbristol.com:5000" ]

run:
  path: sh
  args:
    - -exc
    - |
      source /docker-lib.sh
      start_docker
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      mv dev-certs-output/dev-certs stratos/dev-certs
      cd stratos/deploy/docker-compose/
      ./build.sh -l

