---
platform: linux
inputs:
- name: stratos-ui
- name: dev-certs-output
image_resource:
  type: docker-image
  source:
   repository:  ci-registry.ngrok.io:80/concourse-dcind
   tag: "latest"
   insecure_registries: [ "ci-registry.ngrok.io:80" ]

run:
  path: sh
  args:
    - -ecx
    - |
      source /docker-lib.sh
      start_docker
      # Move dev-certs
      ls .
      mv dev-certs-output/dev-certs stratos-ui/dev-certs
      docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      cd stratos-ui/deploy/kubernetes
      ./build.sh -t test -l
