---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ci-registry.ngrok.io:80/opensuse
    tag: latest
    insecure_registries: [ "ci-registry.ngrok.io:80" ]

inputs:
- name: stratos-ui
outputs:
- name: dev-certs-output
run:
  path: sh
  args:
  - -exc
  - |
    export CERTS_PATH=dev-certs-output/dev-certs
    ./stratos-ui/deploy/tools/generate_cert.sh
