---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

inputs:
- name: stratos-ui
outputs:
- name: dev-certs-output
run:
  path: sh
  args:
  - -exc
  - |
    apk update
    apk add openssl
    export CERTS_PATH=dev-certs-output/dev-certs
    ./stratos-ui/deploy/tools/generate_cert.sh
