# Tag for images
consoleVersion: latest
# Docker Org
dockerOrg: splatform
# Docker Registry where images are available
dockerRegistry: docker.io
# Specify default DB password
dbPassword: changeme
dbProvider: mysql
# Provide Proxy settings if required
#httpProxy: proxy.corp.net
#httpsProxy: proxy.corp.net
#noProxy: localhost
#ftpProxy: proxy.corp.net
#socksProxy: sock-proxy.corp.net
useLb: false
console:
  port: 443
# externalIP: 127.0.0.1
noShared: true
images:
  console: stratos-console
  proxy: stratos-proxy
  proxyNoShared: stratos-proxy-noshared
  postgres: stratos-postgres
  preflight: stratos-preflight-job
  postflight: stratos-postflight-job
# Specify which storage class should be used for PVCs
#storageClass: default
#consoleCert: |
#    -----BEGIN CERTIFICATE-----
#   MIIDXTCCAkWgAwIBAgIJAJooOiQWl1v1MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
#   ...
#    -----END CERTIFICATE-----
#consoleCertKey: |
#    -----BEGIN PRIVATE KEY-----
#    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkdgEAAoIBAQDV9+ySh0xZzM41
#    ...
#    -----END PRIVATE KEYE-----
# MariaDB chart configuration
mariadb:
  # Only required for creating the databases
  mariadbRootPassword: changeme
  image: splatform/stratos-mariadb:10.1.28-r2
  adminUser: root
  # Credentials for user
  mariadbUser: console
  mariadbPassword: changeme
  mariadbDatabase: console
  persistence:
    accessMode: ReadWriteOnce
    size: 1Gi
#    storageClass: default
  metrics:
    enabled: false
uaa:
  protocol: https://
  port: 
  host: 
  consoleClient:  
  consoleClientSecret: 
  consoleAdminIdentifier: 
  skipSSLValidation: false
 # SCF values compatability 
env:
  UAA_HOST: 
  UAA_ADMIN_CLIENT_SECRET: 
  UAA_PORT:
dockerRegistrySecret: