consoleVersion: latest
dockerOrg: splatform
dockerRegistry: docker.io
dbPassword: changeme
images:
  console: stratos-console
  proxy: stratos-proxy
  postgres: stratos-postgres
  preflight: stratos-preflight-job
  postflight: stratos-postflight-job

