basePath: /api/v1
info:
  contact:
    name: Stratos maintainers
    url: https://github.com/cloudfoundry/stratos/issues
  description: Stratos backend API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Stratos API
  version: "1.0"
paths:
  /tokens/{cnsi_guid}:
    delete:
      consumes:
      - application/json
      description: Remove endpoint
      parameters:
      - description: Endpoint GUID
        in: path
        name: cnsi_guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "400": {}
      security:
      - ApiKeyAuth: []
      summary: Remove endpoint
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
