version: '2.3'
services:

  mariadb:
    image: splatform/stratos-dc-mariadb:latest
    env_file:
      ../mariadb.env

  db-migrator:
    image: splatform/stratos-dc-db-migrator:latest
    env_file:
      ../mariadb.env
    links:
    - mariadb:mariadb
    ports:
    - "3306:3306"

  jetstream:
    image: splatform/stratos-dc-jetstream:latest
    ports:
      - "3003:3003"
    env_file:
      ../proxy.env
    links:
      - db-migrator:db-migrator
      - uaa:uaa
      - mariadb:mariadb

  nginx:
    image: splatform/stratos-dc-console:latest
    ports:
      - 80:80
      - 443:443
    links:
      - jetstream:jetstream

  uaa:
    extends:
      file: ../common.yml
      service: uaa

